# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86b5bf94635b094c305722c5daa15a4a0118cd9310518b42c829f2286aa11465a9ebeb9473e7305f723ec19b4957c15fb348c25926017067c139196a28e9f582

test:
  secret_key_base: affdfca48cce1fc2a42d3258542658132dcac2b549e6fef7190f28070947a681238417793231b7a5afb88aa20e1977839a9260f9eb1a3786f0e7bde38b35d1b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
